service: serverless-swapi

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

plugins:
  - serverless-dotenv

custom:
  dotenv:
    path: .env

functions:
  create:
    handler: src/handler.create
    events:
      - http:
          path: crear
          method: post
          cors: true

  listFromDB:
    handler: src/handler.listFromDB
    events:
      - http:
          path: obtener
          method: get
          cors: true

  getFromSwapiAndCreate:
    handler: src/handler.getFromSwapiAndCreate
    events:
      - http:
          path: starwarsToDB/{id}
          method: get
          cors: true

  getFromSwapi:
    handler: src/handler.getFromSwapi
    events:
      - http:
          path: starwars/{id}
          method: get
          cors: true

resources:
  Resources:
    MiTablaDynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: people-from-starwars
        AttributeDefinitions:
          - AttributeName: nombre
            AttributeType: S
        KeySchema:
          - AttributeName: nombre
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
