service: serverless-swapi

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

functions:
  hello:
    handler: src/handler.hello

  create:
    handler: src/handler.create
    events:
      - http:
          path: crear
          method: post
          cors: true

  list:
    handler: src/handler.list
    events:
      - http:
          path: obtener
          method: get
          cors: true

  starWars:
    handler: src/handler.starWars
    events:
      - http:
          path: starwars/{id}
          method: get
          cors: true

resources:
  Resources:
    MiTablaDynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: people-from-starwars
        AttributeDefinitions:
          - AttributeName: nombre
            AttributeType: S
        KeySchema:
          - AttributeName: nombre
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
